name = "ssdi-formal"
version = "0.1.0"
defaultTargets = ["SSDI"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "520045ab14e26149ee970e2e617ca04b09bde5d6"

[[lean_lib]]
name = "SSDI"
